yandex_smart_home:
  entity_config:
    switch.smartintercom_accept_call:
      name: Домофон
      type: devices.types.openable.intercom
      custom_toggles:
        mute:
          state_entity_id: switch.smartintercom_phone_disable
          turn_on:
            action: switch.turn_off
            entity_id: switch.smartintercom_phone_disable
          turn_off:
            action: switch.turn_on
            entity_id: switch.smartintercom_phone_disable
      properties:
        - type: event.motion
          entity: binary_sensor.smartintercom_line_detect
